/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AssetRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetCount"
      | "assets"
      | "owner"
      | "registerAsset"
      | "renounceOwnership"
      | "setAssetActive"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRegistered"
      | "AssetStatusUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assets", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetActive",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "assetCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    name: string,
    assetType: string,
    expectedApyBps: BigNumberish,
    targetAumUsdCents: BigNumberish,
    minimumInvestmentUsdCents: BigNumberish,
    durationDays: BigNumberish,
    priceUsdCents: BigNumberish,
    riskScore: BigNumberish,
    metadataHash: BytesLike,
    creator: AddressLike
  ];
  export type OutputTuple = [
    assetId: string,
    name: string,
    assetType: string,
    expectedApyBps: bigint,
    targetAumUsdCents: bigint,
    minimumInvestmentUsdCents: bigint,
    durationDays: bigint,
    priceUsdCents: bigint,
    riskScore: bigint,
    metadataHash: string,
    creator: string
  ];
  export interface OutputObject {
    assetId: string;
    name: string;
    assetType: string;
    expectedApyBps: bigint;
    targetAumUsdCents: bigint;
    minimumInvestmentUsdCents: bigint;
    durationDays: bigint;
    priceUsdCents: bigint;
    riskScore: bigint;
    metadataHash: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetStatusUpdatedEvent {
  export type InputTuple = [assetId: BytesLike, active: boolean];
  export type OutputTuple = [assetId: string, active: boolean];
  export interface OutputObject {
    assetId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AssetRegistry;
  waitForDeployment(): Promise<this>;

  interface: AssetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetCount: TypedContractMethod<[], [bigint], "view">;

  assets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        name: string;
        assetType: string;
        expectedApyBps: bigint;
        targetAumUsdCents: bigint;
        minimumInvestmentUsdCents: bigint;
        durationDays: bigint;
        priceUsdCents: bigint;
        riskScore: bigint;
        metadataHash: string;
        creator: string;
        createdAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAsset: TypedContractMethod<
    [
      name: string,
      assetType: string,
      expectedApyBps: BigNumberish,
      targetAumUsdCents: BigNumberish,
      minimumInvestmentUsdCents: BigNumberish,
      durationDays: BigNumberish,
      priceUsdCents: BigNumberish,
      riskScore: BigNumberish,
      metadataHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAssetActive: TypedContractMethod<
    [assetId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        name: string;
        assetType: string;
        expectedApyBps: bigint;
        targetAumUsdCents: bigint;
        minimumInvestmentUsdCents: bigint;
        durationDays: bigint;
        priceUsdCents: bigint;
        riskScore: bigint;
        metadataHash: string;
        creator: string;
        createdAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      name: string,
      assetType: string,
      expectedApyBps: BigNumberish,
      targetAumUsdCents: BigNumberish,
      minimumInvestmentUsdCents: BigNumberish,
      durationDays: BigNumberish,
      priceUsdCents: BigNumberish,
      riskScore: BigNumberish,
      metadataHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAssetActive"
  ): TypedContractMethod<
    [assetId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AssetStatusUpdated"
  ): TypedContractEvent<
    AssetStatusUpdatedEvent.InputTuple,
    AssetStatusUpdatedEvent.OutputTuple,
    AssetStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(bytes32,string,string,uint256,uint256,uint256,uint256,uint256,uint256,bytes32,address)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "AssetStatusUpdated(bytes32,bool)": TypedContractEvent<
      AssetStatusUpdatedEvent.InputTuple,
      AssetStatusUpdatedEvent.OutputTuple,
      AssetStatusUpdatedEvent.OutputObject
    >;
    AssetStatusUpdated: TypedContractEvent<
      AssetStatusUpdatedEvent.InputTuple,
      AssetStatusUpdatedEvent.OutputTuple,
      AssetStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
