/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetVaultSol from "./AssetVault.sol";
export type { assetVaultSol };
import type * as rwaExchangeSol from "./RWAExchange.sol";
export type { rwaExchangeSol };
export type { AssetRegistry } from "./AssetRegistry";
export type { RWAToken } from "./RWAToken";
export type { YieldDistributor } from "./YieldDistributor";
