/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RWATokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addYieldComponent"
      | "allowance"
      | "approve"
      | "assetType"
      | "balanceOf"
      | "calculateNetAPY"
      | "clearYieldComponents"
      | "decimals"
      | "duration"
      | "emergencyWithdraw"
      | "expectedAPY"
      | "getAssetInfo"
      | "getExtendedInfo"
      | "getPayoutHistoryCount"
      | "getPayoutRecord"
      | "getRiskLevel"
      | "getUserInvestment"
      | "getYieldComponent"
      | "getYieldComponentsCount"
      | "invest"
      | "investmentAmount"
      | "investmentTime"
      | "isMatured"
      | "maturityDate"
      | "minimumInvestment"
      | "name"
      | "nextPayoutDate"
      | "owner"
      | "paymentToken"
      | "payoutHistory"
      | "recordPayout"
      | "redeem"
      | "renounceOwnership"
      | "riskScore"
      | "scheduleNextPayout"
      | "setPaymentToken"
      | "status"
      | "symbol"
      | "totalAUM"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "updateAPY"
      | "updateAUM"
      | "updateMinimumInvestment"
      | "updateRiskScore"
      | "updateStatus"
      | "updateYieldConfidence"
      | "yieldComponents"
      | "yieldConfidence"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "APYUpdated"
      | "Approval"
      | "Invested"
      | "OwnershipTransferred"
      | "PayoutExecuted"
      | "PayoutScheduled"
      | "Redeemed"
      | "RiskScoreUpdated"
      | "StatusUpdated"
      | "Transfer"
      | "YieldComponentAdded"
      | "YieldConfidenceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addYieldComponent",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "assetType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNetAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clearYieldComponents",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expectedAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExtendedInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayoutHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayoutRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInvestment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldComponent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldComponentsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isMatured", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maturityDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumInvestment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextPayoutDate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payoutHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayout",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "riskScore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "scheduleNextPayout",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalAUM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAPY",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAUM",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinimumInvestment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateYieldConfidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldComponents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldConfidence",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addYieldComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateNetAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearYieldComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExtendedInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayoutHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayoutRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldComponentsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investmentAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investmentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMatured", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maturityDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPayoutDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoutHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "riskScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scheduleNextPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalAUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateAPY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateAUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMinimumInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateYieldConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldComponents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldConfidence",
    data: BytesLike
  ): Result;
}

export namespace APYUpdatedEvent {
  export type InputTuple = [
    oldAPY: BigNumberish,
    newAPY: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [oldAPY: bigint, newAPY: bigint, timestamp: bigint];
  export interface OutputObject {
    oldAPY: bigint;
    newAPY: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestedEvent {
  export type InputTuple = [
    user: AddressLike,
    paymentAmount: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    paymentAmount: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    paymentAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutExecutedEvent {
  export type InputTuple = [
    date: BigNumberish,
    amount: BigNumberish,
    recipientCount: BigNumberish
  ];
  export type OutputTuple = [
    date: bigint,
    amount: bigint,
    recipientCount: bigint
  ];
  export interface OutputObject {
    date: bigint;
    amount: bigint;
    recipientCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutScheduledEvent {
  export type InputTuple = [date: BigNumberish, estimatedAmount: BigNumberish];
  export type OutputTuple = [date: bigint, estimatedAmount: bigint];
  export interface OutputObject {
    date: bigint;
    estimatedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenAmount: BigNumberish,
    paymentAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenAmount: bigint,
    paymentAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenAmount: bigint;
    paymentAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreUpdatedEvent {
  export type InputTuple = [oldScore: BigNumberish, newScore: BigNumberish];
  export type OutputTuple = [oldScore: bigint, newScore: bigint];
  export interface OutputObject {
    oldScore: bigint;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [oldStatus: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [oldStatus: bigint, newStatus: bigint];
  export interface OutputObject {
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldComponentAddedEvent {
  export type InputTuple = [name: string, value: BigNumberish];
  export type OutputTuple = [name: string, value: bigint];
  export interface OutputObject {
    name: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldConfidenceUpdatedEvent {
  export type InputTuple = [
    oldConfidence: BigNumberish,
    newConfidence: BigNumberish
  ];
  export type OutputTuple = [oldConfidence: bigint, newConfidence: bigint];
  export interface OutputObject {
    oldConfidence: bigint;
    newConfidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWAToken extends BaseContract {
  connect(runner?: ContractRunner | null): RWAToken;
  waitForDeployment(): Promise<this>;

  interface: RWATokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addYieldComponent: TypedContractMethod<
    [_name: string, _value: BigNumberish, _description: string],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  assetType: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  calculateNetAPY: TypedContractMethod<[], [bigint], "view">;

  clearYieldComponents: TypedContractMethod<[], [void], "nonpayable">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  duration: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  expectedAPY: TypedContractMethod<[], [bigint], "view">;

  getAssetInfo: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        _assetType: string;
        _expectedAPY: bigint;
        _riskScore: bigint;
        _duration: bigint;
        _nextPayoutDate: bigint;
        _status: bigint;
      }
    ],
    "view"
  >;

  getExtendedInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _yieldConfidence: bigint;
        _totalAUM: bigint;
        _minimumInvestment: bigint;
        _payoutCount: bigint;
        _maturityDate: bigint;
      }
    ],
    "view"
  >;

  getPayoutHistoryCount: TypedContractMethod<[], [bigint], "view">;

  getPayoutRecord: TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        date: bigint;
        amount: bigint;
        recipientCount: bigint;
      }
    ],
    "view"
  >;

  getRiskLevel: TypedContractMethod<[], [string], "view">;

  getUserInvestment: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        _balance: bigint;
        _investmentTime: bigint;
        _investmentAmount: bigint;
        _canRedeem: boolean;
      }
    ],
    "view"
  >;

  getYieldComponent: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, string] & {
        name: string;
        value: bigint;
        description: string;
      }
    ],
    "view"
  >;

  getYieldComponentsCount: TypedContractMethod<[], [bigint], "view">;

  invest: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  investmentAmount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  investmentTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  isMatured: TypedContractMethod<[], [boolean], "view">;

  maturityDate: TypedContractMethod<[], [bigint], "view">;

  minimumInvestment: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  nextPayoutDate: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  payoutHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        date: bigint;
        amount: bigint;
        recipientCount: bigint;
      }
    ],
    "view"
  >;

  recordPayout: TypedContractMethod<
    [_amount: BigNumberish, _recipientCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  redeem: TypedContractMethod<
    [_tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  riskScore: TypedContractMethod<[], [bigint], "view">;

  scheduleNextPayout: TypedContractMethod<
    [_date: BigNumberish, _estimatedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaymentToken: TypedContractMethod<
    [_paymentToken: AddressLike],
    [void],
    "nonpayable"
  >;

  status: TypedContractMethod<[], [bigint], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  totalAUM: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAPY: TypedContractMethod<[_newAPY: BigNumberish], [void], "nonpayable">;

  updateAUM: TypedContractMethod<[_newAUM: BigNumberish], [void], "nonpayable">;

  updateMinimumInvestment: TypedContractMethod<
    [_newMinimum: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRiskScore: TypedContractMethod<
    [_newScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [_newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateYieldConfidence: TypedContractMethod<
    [_newConfidence: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldComponents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string] & {
        name: string;
        value: bigint;
        description: string;
      }
    ],
    "view"
  >;

  yieldConfidence: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addYieldComponent"
  ): TypedContractMethod<
    [_name: string, _value: BigNumberish, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetType"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateNetAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "clearYieldComponents"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "duration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "expectedAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssetInfo"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        _assetType: string;
        _expectedAPY: bigint;
        _riskScore: bigint;
        _duration: bigint;
        _nextPayoutDate: bigint;
        _status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExtendedInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _yieldConfidence: bigint;
        _totalAUM: bigint;
        _minimumInvestment: bigint;
        _payoutCount: bigint;
        _maturityDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPayoutHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayoutRecord"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        date: bigint;
        amount: bigint;
        recipientCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRiskLevel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUserInvestment"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        _balance: bigint;
        _investmentTime: bigint;
        _investmentAmount: bigint;
        _canRedeem: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYieldComponent"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, string] & {
        name: string;
        value: bigint;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYieldComponentsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invest"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "investmentAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "investmentTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isMatured"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "maturityDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumInvestment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextPayoutDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        date: bigint;
        amount: bigint;
        recipientCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordPayout"
  ): TypedContractMethod<
    [_amount: BigNumberish, _recipientCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[_tokenAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scheduleNextPayout"
  ): TypedContractMethod<
    [_date: BigNumberish, _estimatedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<[_paymentToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAPY"
  ): TypedContractMethod<[_newAPY: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAUM"
  ): TypedContractMethod<[_newAUM: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMinimumInvestment"
  ): TypedContractMethod<[_newMinimum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRiskScore"
  ): TypedContractMethod<[_newScore: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<[_newStatus: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateYieldConfidence"
  ): TypedContractMethod<[_newConfidence: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yieldComponents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string] & {
        name: string;
        value: bigint;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "yieldConfidence"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "APYUpdated"
  ): TypedContractEvent<
    APYUpdatedEvent.InputTuple,
    APYUpdatedEvent.OutputTuple,
    APYUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "Invested"
  ): TypedContractEvent<
    InvestedEvent.InputTuple,
    InvestedEvent.OutputTuple,
    InvestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutExecuted"
  ): TypedContractEvent<
    PayoutExecutedEvent.InputTuple,
    PayoutExecutedEvent.OutputTuple,
    PayoutExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutScheduled"
  ): TypedContractEvent<
    PayoutScheduledEvent.InputTuple,
    PayoutScheduledEvent.OutputTuple,
    PayoutScheduledEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreUpdated"
  ): TypedContractEvent<
    RiskScoreUpdatedEvent.InputTuple,
    RiskScoreUpdatedEvent.OutputTuple,
    RiskScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "YieldComponentAdded"
  ): TypedContractEvent<
    YieldComponentAddedEvent.InputTuple,
    YieldComponentAddedEvent.OutputTuple,
    YieldComponentAddedEvent.OutputObject
  >;
  getEvent(
    key: "YieldConfidenceUpdated"
  ): TypedContractEvent<
    YieldConfidenceUpdatedEvent.InputTuple,
    YieldConfidenceUpdatedEvent.OutputTuple,
    YieldConfidenceUpdatedEvent.OutputObject
  >;

  filters: {
    "APYUpdated(uint256,uint256,uint256)": TypedContractEvent<
      APYUpdatedEvent.InputTuple,
      APYUpdatedEvent.OutputTuple,
      APYUpdatedEvent.OutputObject
    >;
    APYUpdated: TypedContractEvent<
      APYUpdatedEvent.InputTuple,
      APYUpdatedEvent.OutputTuple,
      APYUpdatedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "Invested(address,uint256,uint256)": TypedContractEvent<
      InvestedEvent.InputTuple,
      InvestedEvent.OutputTuple,
      InvestedEvent.OutputObject
    >;
    Invested: TypedContractEvent<
      InvestedEvent.InputTuple,
      InvestedEvent.OutputTuple,
      InvestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutExecuted(uint256,uint256,uint256)": TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
    PayoutExecuted: TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;

    "PayoutScheduled(uint256,uint256)": TypedContractEvent<
      PayoutScheduledEvent.InputTuple,
      PayoutScheduledEvent.OutputTuple,
      PayoutScheduledEvent.OutputObject
    >;
    PayoutScheduled: TypedContractEvent<
      PayoutScheduledEvent.InputTuple,
      PayoutScheduledEvent.OutputTuple,
      PayoutScheduledEvent.OutputObject
    >;

    "Redeemed(address,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "RiskScoreUpdated(uint256,uint256)": TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;
    RiskScoreUpdated: TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;

    "StatusUpdated(uint8,uint8)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "YieldComponentAdded(string,int256)": TypedContractEvent<
      YieldComponentAddedEvent.InputTuple,
      YieldComponentAddedEvent.OutputTuple,
      YieldComponentAddedEvent.OutputObject
    >;
    YieldComponentAdded: TypedContractEvent<
      YieldComponentAddedEvent.InputTuple,
      YieldComponentAddedEvent.OutputTuple,
      YieldComponentAddedEvent.OutputObject
    >;

    "YieldConfidenceUpdated(uint256,uint256)": TypedContractEvent<
      YieldConfidenceUpdatedEvent.InputTuple,
      YieldConfidenceUpdatedEvent.OutputTuple,
      YieldConfidenceUpdatedEvent.OutputObject
    >;
    YieldConfidenceUpdated: TypedContractEvent<
      YieldConfidenceUpdatedEvent.InputTuple,
      YieldConfidenceUpdatedEvent.OutputTuple,
      YieldConfidenceUpdatedEvent.OutputObject
    >;
  };
}
