/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RWAToken__factory } from "./RWAToken__factory";
export { YieldDistributor__factory } from "./YieldDistributor__factory";
