/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetRegistry,
  IAssetRegistryInterface,
} from "../../../contracts/AssetVault.sol/IAssetRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
    ],
    name: "assets",
    outputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "assetType",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "expectedApyBps",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "targetAumUsdCents",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minimumInvestmentUsdCents",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "durationDays",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "priceUsdCents",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "riskScore",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "metadataHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "createdAt",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAssetRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetRegistryInterface {
    return new Interface(_abi) as IAssetRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetRegistry {
    return new Contract(address, _abi, runner) as unknown as IAssetRegistry;
  }
}
