/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AssetVault__factory } from "./AssetVault__factory";
export { IAssetRegistry__factory } from "./IAssetRegistry__factory";
