/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAssetRegistryInterface extends Interface {
  getFunction(nameOrSignature: "assets"): FunctionFragment;

  encodeFunctionData(functionFragment: "assets", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
}

export interface IAssetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAssetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assets: TypedContractMethod<
    [assetId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        name: string;
        assetType: string;
        expectedApyBps: bigint;
        targetAumUsdCents: bigint;
        minimumInvestmentUsdCents: bigint;
        durationDays: bigint;
        priceUsdCents: bigint;
        riskScore: bigint;
        metadataHash: string;
        creator: string;
        createdAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean
      ] & {
        name: string;
        assetType: string;
        expectedApyBps: bigint;
        targetAumUsdCents: bigint;
        minimumInvestmentUsdCents: bigint;
        durationDays: bigint;
        priceUsdCents: bigint;
        riskScore: bigint;
        metadataHash: string;
        creator: string;
        createdAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
