/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PlatformRWATokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSupportedToken"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "calculatePaymentAmount"
      | "calculateRWAAmount"
      | "decimals"
      | "emergencyWithdraw"
      | "exchangeMNT"
      | "exchangeToken"
      | "fundMNT"
      | "getStats"
      | "getSupportedTokenIds"
      | "getTokenId"
      | "getTokenInfo"
      | "name"
      | "owner"
      | "redeemToken"
      | "renounceOwnership"
      | "rwaTokenPriceUSD"
      | "supportedTokens"
      | "symbol"
      | "tokenIds"
      | "totalExchanges"
      | "totalSupply"
      | "totalVolumeUSD"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "treasury"
      | "updateRWAPrice"
      | "updateSupportedToken"
      | "updateTreasury"
      | "withdrawMNT"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "OwnershipTransferred"
      | "RWAPriceUpdated"
      | "SupportedTokenAdded"
      | "SupportedTokenUpdated"
      | "TokenExchanged"
      | "TokenRedeemed"
      | "Transfer"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePaymentAmount",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRWAAmount",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeMNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeToken",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fundMNT", values?: undefined): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokenIds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTokenId", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemToken",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rwaTokenPriceUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalExchanges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolumeUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateRWAPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSupportedToken",
    values: [BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMNT",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePaymentAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRWAAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchangeMNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchangeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundMNT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokenIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTokenId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rwaTokenPriceUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalExchanges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolumeUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRWAPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMNT",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RWAPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportedTokenAddedEvent {
  export type InputTuple = [
    tokenId: BytesLike,
    tokenAddress: AddressLike,
    symbol: string
  ];
  export type OutputTuple = [
    tokenId: string,
    tokenAddress: string,
    symbol: string
  ];
  export interface OutputObject {
    tokenId: string;
    tokenAddress: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportedTokenUpdatedEvent {
  export type InputTuple = [
    tokenId: BytesLike,
    newPrice: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    tokenId: string,
    newPrice: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    tokenId: string;
    newPrice: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenExchangedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BytesLike,
    paymentAmount: BigNumberish,
    rwaAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenId: string,
    paymentAmount: bigint,
    rwaAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenId: string;
    paymentAmount: bigint;
    rwaAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRedeemedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BytesLike,
    rwaAmount: BigNumberish,
    paymentAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenId: string,
    rwaAmount: bigint,
    paymentAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenId: string;
    rwaAmount: bigint;
    paymentAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlatformRWAToken extends BaseContract {
  connect(runner?: ContractRunner | null): PlatformRWAToken;
  waitForDeployment(): Promise<this>;

  interface: PlatformRWATokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSupportedToken: TypedContractMethod<
    [
      _tokenId: BytesLike,
      _tokenAddress: AddressLike,
      _priceInUSD: BigNumberish,
      _decimals: BigNumberish,
      _symbol: string
    ],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  calculatePaymentAmount: TypedContractMethod<
    [_tokenId: BytesLike, _rwaAmount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateRWAAmount: TypedContractMethod<
    [_tokenId: BytesLike, _paymentAmount: BigNumberish],
    [bigint],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  exchangeMNT: TypedContractMethod<[], [void], "payable">;

  exchangeToken: TypedContractMethod<
    [_tokenId: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundMNT: TypedContractMethod<[], [void], "payable">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalSupply: bigint;
        _totalVolumeUSD: bigint;
        _totalExchanges: bigint;
        _rwaPrice: bigint;
      }
    ],
    "view"
  >;

  getSupportedTokenIds: TypedContractMethod<[], [string[]], "view">;

  getTokenId: TypedContractMethod<[_symbol: string], [string], "view">;

  getTokenInfo: TypedContractMethod<
    [_tokenId: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        tokenAddress: string;
        priceInUSD: bigint;
        decimals: bigint;
        isActive: boolean;
        symbol: string;
      }
    ],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  redeemToken: TypedContractMethod<
    [_tokenId: BytesLike, _rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rwaTokenPriceUSD: TypedContractMethod<[], [bigint], "view">;

  supportedTokens: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        tokenAddress: string;
        priceInUSD: bigint;
        decimals: bigint;
        isActive: boolean;
        symbol: string;
      }
    ],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalExchanges: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  totalVolumeUSD: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  updateRWAPrice: TypedContractMethod<
    [_newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSupportedToken: TypedContractMethod<
    [_tokenId: BytesLike, _newPrice: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  updateTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawMNT: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<
    [
      _tokenId: BytesLike,
      _tokenAddress: AddressLike,
      _priceInUSD: BigNumberish,
      _decimals: BigNumberish,
      _symbol: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePaymentAmount"
  ): TypedContractMethod<
    [_tokenId: BytesLike, _rwaAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRWAAmount"
  ): TypedContractMethod<
    [_tokenId: BytesLike, _paymentAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exchangeMNT"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "exchangeToken"
  ): TypedContractMethod<
    [_tokenId: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundMNT"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalSupply: bigint;
        _totalVolumeUSD: bigint;
        _totalExchanges: bigint;
        _rwaPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedTokenIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTokenId"
  ): TypedContractMethod<[_symbol: string], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenInfo"
  ): TypedContractMethod<
    [_tokenId: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        tokenAddress: string;
        priceInUSD: bigint;
        decimals: bigint;
        isActive: boolean;
        symbol: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeemToken"
  ): TypedContractMethod<
    [_tokenId: BytesLike, _rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rwaTokenPriceUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        tokenAddress: string;
        priceInUSD: bigint;
        decimals: bigint;
        isActive: boolean;
        symbol: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalExchanges"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolumeUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateRWAPrice"
  ): TypedContractMethod<[_newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSupportedToken"
  ): TypedContractMethod<
    [_tokenId: BytesLike, _newPrice: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawMNT"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RWAPriceUpdated"
  ): TypedContractEvent<
    RWAPriceUpdatedEvent.InputTuple,
    RWAPriceUpdatedEvent.OutputTuple,
    RWAPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SupportedTokenAdded"
  ): TypedContractEvent<
    SupportedTokenAddedEvent.InputTuple,
    SupportedTokenAddedEvent.OutputTuple,
    SupportedTokenAddedEvent.OutputObject
  >;
  getEvent(
    key: "SupportedTokenUpdated"
  ): TypedContractEvent<
    SupportedTokenUpdatedEvent.InputTuple,
    SupportedTokenUpdatedEvent.OutputTuple,
    SupportedTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenExchanged"
  ): TypedContractEvent<
    TokenExchangedEvent.InputTuple,
    TokenExchangedEvent.OutputTuple,
    TokenExchangedEvent.OutputObject
  >;
  getEvent(
    key: "TokenRedeemed"
  ): TypedContractEvent<
    TokenRedeemedEvent.InputTuple,
    TokenRedeemedEvent.OutputTuple,
    TokenRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RWAPriceUpdated(uint256,uint256)": TypedContractEvent<
      RWAPriceUpdatedEvent.InputTuple,
      RWAPriceUpdatedEvent.OutputTuple,
      RWAPriceUpdatedEvent.OutputObject
    >;
    RWAPriceUpdated: TypedContractEvent<
      RWAPriceUpdatedEvent.InputTuple,
      RWAPriceUpdatedEvent.OutputTuple,
      RWAPriceUpdatedEvent.OutputObject
    >;

    "SupportedTokenAdded(bytes32,address,string)": TypedContractEvent<
      SupportedTokenAddedEvent.InputTuple,
      SupportedTokenAddedEvent.OutputTuple,
      SupportedTokenAddedEvent.OutputObject
    >;
    SupportedTokenAdded: TypedContractEvent<
      SupportedTokenAddedEvent.InputTuple,
      SupportedTokenAddedEvent.OutputTuple,
      SupportedTokenAddedEvent.OutputObject
    >;

    "SupportedTokenUpdated(bytes32,uint256,bool)": TypedContractEvent<
      SupportedTokenUpdatedEvent.InputTuple,
      SupportedTokenUpdatedEvent.OutputTuple,
      SupportedTokenUpdatedEvent.OutputObject
    >;
    SupportedTokenUpdated: TypedContractEvent<
      SupportedTokenUpdatedEvent.InputTuple,
      SupportedTokenUpdatedEvent.OutputTuple,
      SupportedTokenUpdatedEvent.OutputObject
    >;

    "TokenExchanged(address,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      TokenExchangedEvent.InputTuple,
      TokenExchangedEvent.OutputTuple,
      TokenExchangedEvent.OutputObject
    >;
    TokenExchanged: TypedContractEvent<
      TokenExchangedEvent.InputTuple,
      TokenExchangedEvent.OutputTuple,
      TokenExchangedEvent.OutputObject
    >;

    "TokenRedeemed(address,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      TokenRedeemedEvent.InputTuple,
      TokenRedeemedEvent.OutputTuple,
      TokenRedeemedEvent.OutputObject
    >;
    TokenRedeemed: TypedContractEvent<
      TokenRedeemedEvent.InputTuple,
      TokenRedeemedEvent.OutputTuple,
      TokenRedeemedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
