/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface YieldDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelScheduledDistribution"
      | "distributeYield(address,uint256,uint256)"
      | "distributeYield(address,uint256,uint256,string)"
      | "distributionCount"
      | "distributions"
      | "emergencyWithdraw"
      | "emergencyWithdrawNative"
      | "executeScheduledDistribution"
      | "getDistribution"
      | "getDistributionsCount"
      | "getRecentDistributions"
      | "getScheduledCount"
      | "getScheduledDistribution"
      | "getTokenStats"
      | "owner"
      | "renounceOwnership"
      | "scheduleDistribution"
      | "scheduledDistributions"
      | "totalDistributed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DistributionCancelled"
      | "DistributionExecuted"
      | "DistributionScheduled"
      | "OwnershipTransferred"
      | "YieldDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelScheduledDistribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeYield(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeYield(address,uint256,uint256,string)",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "distributionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeScheduledDistribution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistributionsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentDistributions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduledCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduledDistribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleDistribution",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduledDistributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDistributed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelScheduledDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeYield(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeYield(address,uint256,uint256,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeScheduledDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistributionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentDistributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduledCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduledDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduledDistributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DistributionCancelledEvent {
  export type InputTuple = [scheduleId: BigNumberish, token: AddressLike];
  export type OutputTuple = [scheduleId: bigint, token: string];
  export interface OutputObject {
    scheduleId: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributionExecutedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributionScheduledEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    scheduledDate: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    token: string,
    amount: bigint,
    scheduledDate: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    token: string;
    amount: bigint;
    scheduledDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDistributedEvent {
  export type InputTuple = [
    token: AddressLike,
    totalAmount: BigNumberish,
    recipientCount: BigNumberish,
    timestamp: BigNumberish,
    distributionType: string
  ];
  export type OutputTuple = [
    token: string,
    totalAmount: bigint,
    recipientCount: bigint,
    timestamp: bigint,
    distributionType: string
  ];
  export interface OutputObject {
    token: string;
    totalAmount: bigint;
    recipientCount: bigint;
    timestamp: bigint;
    distributionType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): YieldDistributor;
  waitForDeployment(): Promise<this>;

  interface: YieldDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelScheduledDistribution: TypedContractMethod<
    [_scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "distributeYield(address,uint256,uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _totalAmount: BigNumberish,
      _recipientCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "distributeYield(address,uint256,uint256,string)": TypedContractMethod<
    [
      _token: AddressLike,
      _totalAmount: BigNumberish,
      _recipientCount: BigNumberish,
      _distributionType: string
    ],
    [void],
    "nonpayable"
  >;

  distributionCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  distributions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        token: string;
        totalAmount: bigint;
        recipientCount: bigint;
        timestamp: bigint;
        distributionType: string;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawNative: TypedContractMethod<[], [void], "nonpayable">;

  executeScheduledDistribution: TypedContractMethod<
    [_scheduleId: BigNumberish, _recipientCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDistribution: TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        token: string;
        totalAmount: bigint;
        recipientCount: bigint;
        timestamp: bigint;
        distributionType: string;
      }
    ],
    "view"
  >;

  getDistributionsCount: TypedContractMethod<[], [bigint], "view">;

  getRecentDistributions: TypedContractMethod<
    [_token: AddressLike, _limit: BigNumberish],
    [
      [bigint[], bigint[], bigint[]] & {
        amounts: bigint[];
        timestamps: bigint[];
        recipients: bigint[];
      }
    ],
    "view"
  >;

  getScheduledCount: TypedContractMethod<[], [bigint], "view">;

  getScheduledDistribution: TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        token: string;
        amount: bigint;
        scheduledDate: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  getTokenStats: TypedContractMethod<
    [_token: AddressLike],
    [
      [bigint, bigint] & {
        _totalDistributed: bigint;
        _distributionCount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scheduleDistribution: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish, _scheduledDate: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  scheduledDistributions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        token: string;
        amount: bigint;
        scheduledDate: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  totalDistributed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelScheduledDistribution"
  ): TypedContractMethod<[_scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeYield(address,uint256,uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _totalAmount: BigNumberish,
      _recipientCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeYield(address,uint256,uint256,string)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _totalAmount: BigNumberish,
      _recipientCount: BigNumberish,
      _distributionType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        token: string;
        totalAmount: bigint;
        recipientCount: bigint;
        timestamp: bigint;
        distributionType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawNative"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeScheduledDistribution"
  ): TypedContractMethod<
    [_scheduleId: BigNumberish, _recipientCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDistribution"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        token: string;
        totalAmount: bigint;
        recipientCount: bigint;
        timestamp: bigint;
        distributionType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDistributionsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecentDistributions"
  ): TypedContractMethod<
    [_token: AddressLike, _limit: BigNumberish],
    [
      [bigint[], bigint[], bigint[]] & {
        amounts: bigint[];
        timestamps: bigint[];
        recipients: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScheduledCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScheduledDistribution"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        token: string;
        amount: bigint;
        scheduledDate: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenStats"
  ): TypedContractMethod<
    [_token: AddressLike],
    [
      [bigint, bigint] & {
        _totalDistributed: bigint;
        _distributionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleDistribution"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish, _scheduledDate: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduledDistributions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        token: string;
        amount: bigint;
        scheduledDate: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalDistributed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DistributionCancelled"
  ): TypedContractEvent<
    DistributionCancelledEvent.InputTuple,
    DistributionCancelledEvent.OutputTuple,
    DistributionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "DistributionExecuted"
  ): TypedContractEvent<
    DistributionExecutedEvent.InputTuple,
    DistributionExecutedEvent.OutputTuple,
    DistributionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DistributionScheduled"
  ): TypedContractEvent<
    DistributionScheduledEvent.InputTuple,
    DistributionScheduledEvent.OutputTuple,
    DistributionScheduledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "YieldDistributed"
  ): TypedContractEvent<
    YieldDistributedEvent.InputTuple,
    YieldDistributedEvent.OutputTuple,
    YieldDistributedEvent.OutputObject
  >;

  filters: {
    "DistributionCancelled(uint256,address)": TypedContractEvent<
      DistributionCancelledEvent.InputTuple,
      DistributionCancelledEvent.OutputTuple,
      DistributionCancelledEvent.OutputObject
    >;
    DistributionCancelled: TypedContractEvent<
      DistributionCancelledEvent.InputTuple,
      DistributionCancelledEvent.OutputTuple,
      DistributionCancelledEvent.OutputObject
    >;

    "DistributionExecuted(uint256,address,uint256,uint256)": TypedContractEvent<
      DistributionExecutedEvent.InputTuple,
      DistributionExecutedEvent.OutputTuple,
      DistributionExecutedEvent.OutputObject
    >;
    DistributionExecuted: TypedContractEvent<
      DistributionExecutedEvent.InputTuple,
      DistributionExecutedEvent.OutputTuple,
      DistributionExecutedEvent.OutputObject
    >;

    "DistributionScheduled(uint256,address,uint256,uint256)": TypedContractEvent<
      DistributionScheduledEvent.InputTuple,
      DistributionScheduledEvent.OutputTuple,
      DistributionScheduledEvent.OutputObject
    >;
    DistributionScheduled: TypedContractEvent<
      DistributionScheduledEvent.InputTuple,
      DistributionScheduledEvent.OutputTuple,
      DistributionScheduledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "YieldDistributed(address,uint256,uint256,uint256,string)": TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
    YieldDistributed: TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
  };
}
